=== blumatix/BluDoc/schema/BluDoc_Schema_V1.5.0.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://schemas.blumatix.com/bludelta/bludoc/v1.5.0/schema.json",
    "title": "BluDoc Schema",
    "description": "BluDoc is a multi-layer document description format enabling exchange with AI in mind",
    "$ref": "#/definitions/BluDoc",
    "definitions": {
      "BluDoc": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "BluDoc.Version": {
            "type": "string",
            "description": "The version of the BluDoc format."
          },
          "DocumentProvider.Name": {
            "type": "string",
            "description": "The name of the document provider."
          },
          "Created.DateTime": {
            "type": "string",
            "format": "date-time",
            "description": "The date and time when the document was created."
          },
          "CreatorSoftware.Name": {
            "type": "string",
            "description": "The name of the software used to create the document."
          },
          "CreatorSoftware.Version": {
            "type": "string",
            "description": "The version of the software used to create the document."
          },
          "Document.Type": {
            "type": "string",
            "description": "The type of the document."
          },
          "Document.Languages": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[a-z]{2}$"
            },
            "description": "The list of languages used in the document, represented by their ISO 639-1 codes"
          },
          "Pages": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/Page"
            },
            "description": "An array of pages in the document."
          },
          "DocumentEssentials": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/DocumentEssential"
            },
            "description": "An array of essential document details."
          },
          "DocumentTexts": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Line": {
                  "$ref": "#/definitions/Line"
                }
              },
              "required": [ "Line" ]
            },
            "description": "An array of lines of text in the document.",
            "additionalProperties": false,
            "title": "LineWrapper"
          },
          "DocumentBinaries": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/DocumentBinary"
            },
            "description": "An array of binary representation of the document."
          }
        },
        "required": [
          "BluDoc.Version",
          "Created.DateTime",
          "DocumentProvider.Name",
          "Document.Type"
        ],
        "title": "BluDoc",
        "description": "The root object representing a BluDoc document."
      },
      "DocumentEssential": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "Label": {
            "type": "string",
            "description": "The label of the document essential."
          },
          "Value": {
            "type": [ "string", "null" ],
            "description": "The value of the document essential, if applicable."
          },
          "Text": {
            "type": [ "string", "null" ],
            "description": "The text representation of the document essential, if applicable."
          },
          "Location": {
            "type": [ "null", "object" ],
            "$ref": "#/definitions/Location",
            "description": "The location details of the document essential, if applicable."
          },
          "Confidence": {
            "type": "number",
            "minimum": -1,
            "maximum": 1,
            "description": "The confidence level (0.0-1.0) associated with the document essential. Score of -1 indicates no confidence score."
          },
          "ConfidenceThreshold": {
            "type": "number",
            "description": "The threshold value used to determine the confidence level."
          },
          "Items": {
            "type": [ "array", "null" ],
            "items": {
              "$ref": "#/definitions/DocumentEssential"
            },
            "description": "An array of sub-items representing additional document essentials, if applicable."
          }
        },
        "required": [
          "Label"
        ],
        "title": "DocumentEssential"
      },
      "DocumentBinary": {
        "type": "object",
        "properties": {
          "ContentType": {
            "type": "string",
            "description": "Describes the nature or purpose of the binary content, specifying how the content is intended to be used or its format characteristics."
          },
          "MediaType": {
            "type": "string",
            "description": "The media type of the binary content, e.g., image/png or application/pdf."
          },
          "FileName": {
            "type": "string",
            "description": "The file name of the content, e.g., attachment1.pdf"
          },
          "Name": {
            "type": "string",
            "description": "The name of the content, e.g., attachment1"
          },
          "Embedding": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "An array of Base64 encoded data strings. For multi-page images, each page is represented as a separate Base64 encoded string. For PDFs, the entire document, regardless of page count, is represented by a single Base64 encoded string."
          },
          "Reference": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "uri"
            },
            "description": "URL references to the binary content."
          }
        },
        "required": [ "ContentType", "MediaType" ],
        "oneOf": [
          {
            "required": [ "Embedding" ]
          },
          {
            "required": [ "Reference" ]
          }
        ]
      },
      "Line": {
        "type": "object",
        "properties": {
          "Text": {
            "type": "string",
            "description": "The concatenated text of all words in the line."
          },
          "Location": {
            "type": "object",
            "$ref": "#/definitions/Location",
            "description": "The location details of the line."
          },
          "Words": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/Word"
            },
            "description": "The individual words within the line."
          }
        },
        "required": [ "Text", "Location", "Words" ],
        "title": "Line"
      },
      "Word": {
        "type": "object",
        "properties": {
          "Text": {
            "type": "string",
            "description": "The text of the word."
          },
          "Location": {
            "type": "object",
            "$ref": "#/definitions/Location",
            "description": "The location details of the word."
          }
        },
        "required": [ "Text", "Location" ],
        "title": "Word"
      },
      "Location": {
        "type": [ "object", "null" ],
        "additionalProperties": false,
        "properties": {
          "Page": {
            "type": "integer",
            "description": "The page number where the element is located."
          },
          "Left": {
            "type": "integer",
            "description": "The position of the element from the left on the page in pixels."
          },
          "Top": {
            "type": "integer",
            "description": "The position of the element from the top on the page in pixels."
          },
          "Width": {
            "type": "integer",
            "description": "The width of the element in pixels."
          },
          "Height": {
            "type": "integer",
            "description": "The height of the element in pixels."
          }
        },
        "required": [
          "Left",
          "Top",
          "Width",
          "Height",
          "Page"
        ],
        "title": "Location"
      },
      "Page": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "Id": {
            "type": "integer",
            "description": "The page number.",
            "minimum": 1
          },
          "Width": {
            "type": "integer",
            "description": "The width of the page in pixels."
          },
          "Height": {
            "type": "integer",
            "description": "The height of the page in pixels."
          },
          "Dpi": {
            "type": "integer",
            "description": "The dots per inch (DPI) of the page."
          },
          "Orientation": {
            "type": "string",
            "description": "The orientation of the page (e.g., Portrait or Landscape).",
            "enum": [ "Portrait", "Landscape" ]
          },
          "AppliedRotationDegreesClockwise": {
            "type": "integer",
            "description": "The rotation applied to the page in degrees clockwise."
          }
        },
        "required": [
          "Width",
          "Height",
          "Dpi",
          "Id"
        ],
        "title": "Page"
      }
    }
  }

=== blumatix/BluDoc/samples/order/bludoc_order_sample.json
{
  "BluDoc.Version": "1.5.0",
  "Created.DateTime": "2026-01-27T10:37:22.0093338+00:00",
  "CreatorSoftware.Name": "DocumentWorkflow",
  "CreatorSoftware.Version": "1.0.0",
  "Document.Type": "order",
  "DocumentEssentials": [
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": null,
      "Label": "Order.Id",
      "Location": {
        "Height": 50,
        "Left": 1317,
        "Page": 1,
        "Top": 995,
        "Width": 141
      },
      "Text": "123456",
      "Value": "123456"
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": null,
      "Label": "Order.Date",
      "Location": {
        "Height": 41,
        "Left": 1129,
        "Page": 1,
        "Top": 1056,
        "Width": 214
      },
      "Text": "02.05.2025",
      "Value": "2025-05-02"
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": null,
      "Label": "Sender.Id",
      "Location": {
        "Height": 44,
        "Left": 617,
        "Page": 1,
        "Top": 999,
        "Width": 250
      },
      "Text": "1000030 000",
      "Value": "1000030 000"
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": null,
      "Label": "Receiver.Id",
      "Location": {
        "Height": 41,
        "Left": 606,
        "Page": 1,
        "Top": 1050,
        "Width": 94
      },
      "Text": "1234",
      "Value": "1234"
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": null,
      "Label": "Sender.VatId",
      "Location": {
        "Height": 51,
        "Left": 431,
        "Page": 1,
        "Top": 753,
        "Width": 295
      },
      "Text": "ATU12345678",
      "Value": "ATU12345678"
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": [
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Name",
          "Location": {
            "Height": 54,
            "Left": 1650,
            "Page": 1,
            "Top": 290,
            "Width": 675
          },
          "Text": "Blumatix Intelligence GmbH",
          "Value": "Blumatix Intelligence GmbH"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Attention.Name",
          "Location": null,
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Street",
          "Location": {
            "Height": 50,
            "Left": 1950,
            "Page": 1,
            "Top": 352,
            "Width": 377
          },
          "Text": "Schwarzstraße 48",
          "Value": "Schwarzstraße 48"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.ZipCode",
          "Location": null,
          "Text": "5020",
          "Value": "5020"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.City",
          "Location": null,
          "Text": "Salzburg",
          "Value": "Salzburg"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Region",
          "Location": null,
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Country",
          "Location": null,
          "Text": "Austria",
          "Value": "AT"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Website",
          "Location": {
            "Height": 37,
            "Left": 819,
            "Page": 1,
            "Top": 3150,
            "Width": 296
          },
          "Text": "www.blumatix.com",
          "Value": "https://blumatix.com"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Email",
          "Location": null,
          "Text": "office@blumatix.com",
          "Value": "office@blumatix.com"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Phone",
          "Location": {
            "Height": 48,
            "Left": 1975,
            "Page": 1,
            "Top": 475,
            "Width": 350
          },
          "Text": "+43 662 243410",
          "Value": "+43662243410"
        }
      ],
      "Label": "Sender.Contact.Item",
      "Location": null,
      "Text": null,
      "Value": null
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": [
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "ReceiverArticle.Id",
          "Location": {
            "Height": 39,
            "Left": 556,
            "Page": 1,
            "Top": 1665,
            "Width": 243
          },
          "Text": "100.010.0001",
          "Value": "100.010.0001"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Article.Id",
          "Location": {
            "Height": 42,
            "Left": 901,
            "Page": 1,
            "Top": 1748,
            "Width": 110
          },
          "Text": "84526",
          "Value": "84526"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Quantity.Decimal",
          "Location": null,
          "Text": "10",
          "Value": "10"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Unit.Type",
          "Location": null,
          "Text": "Stück",
          "Value": "Stück"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Unit.SmallAmount",
          "Location": null,
          "Text": "20",
          "Value": "20.0000"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "DeliveryDate.Item",
          "Location": null,
          "Text": null,
          "Value": null
        }
      ],
      "Label": "Line.Item",
      "Location": null,
      "Text": null,
      "Value": null
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": [
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "ReceiverArticle.Id",
          "Location": {
            "Height": 51,
            "Left": 549,
            "Page": 1,
            "Top": 1824,
            "Width": 236
          },
          "Text": "202.305.202",
          "Value": "202.305.202"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Article.Id",
          "Location": {
            "Height": 53,
            "Left": 901,
            "Page": 1,
            "Top": 1909,
            "Width": 113
          },
          "Text": "75468",
          "Value": "75468"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Quantity.Decimal",
          "Location": null,
          "Text": "10",
          "Value": "10"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Unit.Type",
          "Location": null,
          "Text": "Stück",
          "Value": "Stück"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Unit.SmallAmount",
          "Location": null,
          "Text": "30",
          "Value": "30.0000"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "DeliveryDate.Item",
          "Location": null,
          "Text": null,
          "Value": null
        }
      ],
      "Label": "Line.Item",
      "Location": null,
      "Text": null,
      "Value": null
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": [
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Delivery.Date",
          "Location": {
            "Height": 43,
            "Left": 535,
            "Page": 1,
            "Top": 1104,
            "Width": 216
          },
          "Text": "05.05.2025",
          "Value": "2025-05-05"
        },
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Delivery.Week",
          "Location": null,
          "Text": "KW19/2025",
          "Value": ""
        }
      ],
      "Label": "DeliveryDate.Item",
      "Location": null,
      "Text": null,
      "Value": null
    },
    {
      "Confidence": 0.85,
      "ConfidenceThreshold": -1.0,
      "Items": [
        {
          "Confidence": 0.85,
          "ConfidenceThreshold": -1.0,
          "Items": null,
          "Label": "Contact.Name",
          "Location": {
            "Height": 54,
            "Left": 1650,
            "Page": 1,
            "Top": 290,
            "Width": 675
          },
          "Text": "Blumatix Intelligence GmbH",
          "Value": "Blumatix Intelligence GmbH"
        },
        {
