=== blumatix/BluDoc/schema/BluDoc_Schema_V1.3.0.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://schemas.blumatix.com/bludelta/bludoc/v1.3.0/schema.json",
  "title": "BluDoc Schema",
  "description": "BluDoc is a multi-layer document description format enabling exchange with AI in mind",
  "$ref": "#/definitions/BluDoc",
  "definitions": {
    "BluDoc": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "BluDoc.Version": {
          "type": "string",
          "description": "The version of the BluDoc format."
        },
        "DocumentProvider.Name": {
          "type": "string",
          "description": "The name of the document provider."
        },
        "Created.DateTime": {
          "type": "string",
          "format": "date-time",
          "description": "The date and time when the document was created."
        },
        "CreatorSoftware.Name": {
          "type": "string",
          "description": "The name of the software used to create the document."
        },
        "CreatorSoftware.Version": {
          "type": "string",
          "description": "The version of the software used to create the document."
        },
        "Document.Type": {
          "type": "string",
          "description": "The type of the document."
        },
        "Document.Languages": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[a-z]{2}$"
          },
          "description": "The list of languages used in the document, represented by their ISO 639-1 codes"
        },
        "Pages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Page"
          },
          "description": "An array of pages in the document."
        },
        "DocumentEssentials": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/DocumentEssential"
          },
          "description": "An array of essential document details."
        },
        "DocumentTexts" :{
          "type": "array",
          "items": {
            "type" : "object",
            "properties": {
              "Line": {
                "$ref": "#/definitions/Line"
              }
            }
          },
          "description" : "An array of lines of text in the document.",
          "additionalProperties": false,
          "required": ["Line"],
          "title": "LineWrapper"
        }
      },
      "required": [
        "BluDoc.Version",
        "Created.DateTime",
        "DocumentProvider.Name",
        "Document.Type"
      ],
      "title": "BluDoc",
      "description": "The root object representing a BluDoc document."
    },
    "DocumentEssential": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Label": {
          "type": "string",
          "description": "The label of the document essential."
        },
        "Value": {
          "type": [ "string", "null" ],
          "description": "The value of the document essential, if applicable."
        },
        "Text": {
          "type": [ "string", "null" ],
          "description": "The text representation of the document essential, if applicable."
        },
        "Location": {
          "type": [ "null", "object" ],
          "$ref": "#/definitions/Location",
          "description": "The location details of the document essential, if applicable."
        },
        "Confidence": {
          "type": "number",
          "minimum": 0,
          "maximum": 1,
          "description": "The confidence level associated with the document essential."
        },
        "ConfidenceThreshold": {
          "type": "number",
          "description": "The threshold value used to determine the confidence level."
        },
        "Items": {
          "type": [ "array", "null" ],
          "items": {
            "$ref": "#/definitions/DocumentEssential"
          },
          "description": "An array of sub-items representing additional document essentials, if applicable."
        }
      },
      "required": [
        "Label"
      ],
      "title": "DocumentEssential"
    },
    "Line": {
      "type": "object",
      "properties": {
        "Text": {
          "type": "string",
          "description": "The concatenated text of all words in the line."
        },
        "Location": {
          "type": "object",
          "$ref": "#/definitions/Location",
          "description": "The location details of the line."
        },
        "Words": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Word"
          },
          "description": "The individual words within the line."
        }
      },
      "required": ["Text", "Location", "Words"],
      "title": "Line"
    },
    "Word": {
      "type": "object",
      "properties": {
        "Text": {
          "type": "string",
          "description": "The text of the word."
        },
        "Location": {
          "type": "object",
          "$ref": "#/definitions/Location",
          "description": "The location details of the word."
        }
      },
      "required": ["Text", "Location"],
      "title": "Word"
    },
    "Location": {
      "type": [ "object", "null" ],
      "additionalProperties": false,
      "properties": {
        "Page": {
          "type": "integer",
          "description": "The page number where the element is located."
        },
        "Left": {
          "type": "integer",
          "description": "The position of the element from the left on the page in pixels."
        },
        "Top": {
          "type": "integer",
          "description": "The position of the element from the top on the page in pixels."
        },
        "Width": {
          "type": "integer",
          "description": "The width of the element in pixels."
        },
        "Height": {
          "type": "integer",
          "description": "The height of the element in pixels."
        }
      },
      "required": [
        "Left",
        "Top",
        "Width",
        "Height",
        "Page"
      ],
      "title": "Location"
    },
    "Page": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Id": {
          "type": "integer",
          "description": "The page number.",
          "minimum": 1
        },
        "Width": {
          "type": "integer",
          "description": "The width of the page in pixels."
        },
        "Height": {
          "type": "integer",
          "description": "The height of the page in pixels."
        },
        "Dpi": {
          "type": "integer",
          "description": "The dots per inch (DPI) of the page."
        },
        "Orientation": {
          "type": "string",
          "description": "The orientation of the page (e.g., Portrait or Landscape).",
          "enum": [ "Portrait", "Landscape" ]
        }
      },
      "required": [
        "Width",
        "Height",
        "Dpi",
        "Id"
      ],
      "title": "Page"
    }
  }
}

=== blumatix/BluDoc/samples/quotation/bludoc-quotation-sample-v1.json
{
  "BluDoc.Version": "1.4.0",
  "Created.DateTime": "2024-06-12T15:03:13.9086976+00:00",
  "CreatorSoftware.Name": "quotation",
  "CreatorSoftware.Version": "v0.1.0",
  "Document.Languages": [
    "de"
  ],
  "Document.Type": "Quotation",
  "DocumentEssentials": [
    {
      "Confidence": 0.6393,
      "ConfidenceThreshold": -1,
      "Label": "Quotation.Id",
      "Location": {
        "Height": 35,
        "Left": 2163,
        "Page": 1,
        "Top": 1372,
        "Width": 147
      },
      "Text": "898989",
      "Value": "898989"
    },
    {
      "Confidence": 0.9394,
      "ConfidenceThreshold": -1,
      "Label": "Quotation.Date",
      "Location": {
        "Height": 35,
        "Left": 2088,
        "Page": 1,
        "Top": 1427,
        "Width": 223
      },
      "Text": "02.05.2024",
      "Value": "2024-05-02"
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "ReceiverOrder.Id",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0.9802,
      "ConfidenceThreshold": -1,
      "Label": "GrandTotal.Amount",
      "Location": {
        "Height": 31,
        "Left": 2131,
        "Page": 1,
        "Top": 2762,
        "Width": 96
      },
      "Text": "241,08",
      "Value": "241.08"
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "VatId",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0.9997,
      "ConfidenceThreshold": -1,
      "Label": "Sender.VatId",
      "Location": {
        "Height": 35,
        "Left": 2001,
        "Page": 1,
        "Top": 679,
        "Width": 283
      },
      "Text": "ATU70948479",
      "Value": "ATU70948479"
    },
    {
      "Confidence": 0.9996,
      "ConfidenceThreshold": -1,
      "Label": "Receiver.VatId",
      "Location": {
        "Height": 35,
        "Left": 524,
        "Page": 1,
        "Top": 944,
        "Width": 284
      },
      "Text": "ATU12345678",
      "Value": "ATU12345678"
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "Automotive.Plate.Id",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "Automotive.Vin.Id",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "Automotive.Mileage",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "Automotive.FirstRegistration.Date",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "Sender.TaxId",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Label": "Receiver.TaxId",
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0.8267834782600403,
      "ConfidenceThreshold": -1,
      "Items": [
        {
          "Confidence": 0.9691,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Name",
          "Location": {
            "Height": 32,
            "Left": 265,
            "Page": 1,
            "Top": 3117,
            "Width": 420
          },
          "Text": "Blumatix Intelligence GmbH",
          "Value": "Blumatix Intelligence GmbH"
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Attention.Name",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0.9652,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Street",
          "Location": {
            "Height": 26,
            "Left": 264,
            "Page": 1,
            "Top": 3157,
            "Width": 268
          },
          "Text": "Schwarzstraße 48",
          "Value": "Schwarzstraße 48"
        },
        {
          "Confidence": 0.9368,
          "ConfidenceThreshold": -1,
          "Label": "Contact.ZipCode",
          "Location": {
            "Height": 26,
            "Left": 264,
            "Page": 1,
            "Top": 3198,
            "Width": 68
          },
          "Text": "5020",
          "Value": "5020"
        },
        {
          "Confidence": 0.9402,
          "ConfidenceThreshold": -1,
          "Label": "Contact.City",
          "Location": {
            "Height": 32,
            "Left": 351,
            "Page": 1,
            "Top": 3198,
            "Width": 120
          },
          "Text": "Salzburg",
          "Value": "Salzburg"
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Region",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Country",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Website",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Email",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Phone",
          "Text": "",
          "Value": ""
        }
      ],
      "Label": "Sender.Contact.Item",
      "Location": {
        "Height": 127,
        "Left": 258,
        "Page": 1,
        "Top": 3123,
        "Width": 449
      },
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0.6635317802429199,
      "ConfidenceThreshold": -1,
      "Items": [
        {
          "Confidence": 0.9664,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Name",
          "Location": {
            "Height": 36,
            "Left": 243,
            "Page": 1,
            "Top": 638,
            "Width": 556
          },
          "Text": "Max Mustermann GmbH",
          "Value": "Max Mustermann GmbH"
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Attention.Name",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0.9648,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Street",
          "Location": {
            "Height": 35,
            "Left": 243,
            "Page": 1,
            "Top": 699,
            "Width": 248
          },
          "Text": "Musterstr. 8",
          "Value": "Musterstr. 8"
        },
        {
          "Confidence": 0.9893,
          "ConfidenceThreshold": -1,
          "Label": "Contact.ZipCode",
          "Location": {
            "Height": 35,
            "Left": 241,
            "Page": 1,
            "Top": 762,
            "Width": 122
          },
          "Text": "80538",
          "Value": "80538"
        },
        {
          "Confidence": 0.9832,
          "ConfidenceThreshold": -1,
          "Label": "Contact.City",
          "Location": {
            "Height": 36,
            "Left": 388,
            "Page": 1,
            "Top": 761,
            "Width": 175
          },
          "Text": "München",
          "Value": "München"
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Region",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0.9897,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Country",
          "Location": {
            "Height": 36,
            "Left": 243,
            "Page": 1,
            "Top": 821,
            "Width": 239
          },
          "Text": "Deutschland",
          "Value": "DE"
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Website",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Email",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Phone",
          "Text": "",
          "Value": ""
        }
      ],
      "Label": "Receiver.Contact.Item",
      "Location": {
        "Height": 236,
        "Left": 239,
        "Page": 1,
        "Top": 638,
        "Width": 587
      },
      "Text": "",
      "Value": ""
    },
    {
      "Confidence": 0,
      "ConfidenceThreshold": -1,
      "Items": [
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Name",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Attention.Name",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Street",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.ZipCode",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.City",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Region",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Country",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
          "Label": "Contact.Website",
          "Text": "",
          "Value": ""
        },
        {
          "Confidence": 0,
          "ConfidenceThreshold": -1,
